"""Front-page pipeline: DivergenceBrief -> illustrated newspaper image in B2.

The image is generated by GMICloud (Seedream), with a fallback model so a single
model outage does not fail the batch, then routed through the synthetic-content
watermark before upload. The pipeline carries the simulation provenance block, so
the stored manifest's canonical hash is bound to the fork.

Requires GMI_API_KEY and B2 credentials; everything it depends on below the
network boundary (prompt, provenance, watermark, index shape) is tested offline.
"""
from __future__ import annotations

import os

from genblaze_core import Modality, Pipeline

from ..contracts import DivergenceBrief
from ..pricing import register_pricing
from ..prompts import front_page_prompt
from ..provenance import apply_provenance
from ..storage import backblaze_sink

PRIMARY_MODEL = "seedream-5.0-lite"
# Proven by forcing a failure in tests: an unusable primary must fall through.
FALLBACK_MODELS = ["flux-1-schnell"]


def build_pipeline(brief: DivergenceBrief, *, primary: str = PRIMARY_MODEL) -> Pipeline:
    """Construct the pipeline for one front page. No network until .run()."""
    from genblaze_gmicloud import GMICloudImageProvider

    provider = GMICloudImageProvider(api_key=os.environ.get("GMI_API_KEY"))
    register_pricing(provider)

    pipeline = Pipeline(f"front-page-{brief.fork_id}-{brief.nation_iso}-{brief.sim_date.year}",
                        tenant_id=brief.fork_id)
    pipeline = apply_provenance(pipeline, brief)
    pipeline.step(
        provider,
        model=primary,
        prompt=front_page_prompt(brief),
        modality=Modality.IMAGE,
        fallback_models=FALLBACK_MODELS,
        params={"aspect_ratio": "3:4", "resolution": "1024x1365"},
    )
    return pipeline


def generate_front_page(brief: DivergenceBrief, *, timeout: float = 180.0):
    """Run the pipeline to B2 and return the PipelineResult.

    A fresh sink per run: ObjectStorageSink closes run-scoped resources when the
    run finishes, so it is single-use.
    """
    return build_pipeline(brief).run(sink=backblaze_sink(), timeout=timeout)
